<a href="https://colab.research.google.com/github/neysin/orm/blob/main/0104_%EC%8B%9C%ED%80%80%EC%8A%A4%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 시퀀스 자료형


In [2]:
# 1.1 인덱싱
          #54321    <- (-)일 때
          #01234
example = 'abcde'
print(example[0]) # 출력: a
print(example[2]) # 출력: c
print(example[-1])

a
c
e


In [4]:
# 1.2 슬라이싱
          #01234
example = 'abcde'
print(example[1:3]) # 출력: bc
print(example[-4:-1])


bc
bcd


In [ ]:
range(10)[3] # 출력: 3
range(100)[::5] # 출력: range(0, 100, 5)

In [7]:
# 1.3 특정항목 포함 여부

example = 'abcde'
print('a' in example ) # 출력: True
print('z' in example) # 출력: False

True
False


In [8]:
# 1.4 연결 및 반복

example1 = 'abcde'
example2 = 'f'
print(example1 + example2) # 출력: abcdef
print(example2 * 3)        # 출력: fff

abcdef
fff


In [9]:
# 1.5 내장 함수

example = 'abcde'
print(len(example))  # 출력: 5
print(min(example))  # 출력: a
print(max(example))  # 출력: e

5
a
e


# 2. 시퀀스 자료형의 패킹과 언패킹

In [11]:
# 2.1 튜플 패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)  # 출력: (1, 2, 3, 4)

a= 1,2,3,4
print(a)
print(type(a))
print(dir(a))

(1, 2, 3, 4)
(1, 2, 3, 4)
<class 'tuple'>
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


In [14]:
# 2.2 언패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4

# 튜플 언패킹
a, b, c, d = packed_tuple
print(a)  # 출력: 1
print(b)  # 출력: 2
print(c)
print(d)

1
2
3
4


In [15]:
# 다양한 패킹/언패킹
# range는 범위안의 숫자를 생성함.

a, b, c = range(3) #range(3)이 0, 1, 2 를 생성
a # 출력: 0
print(range(3))
print(a,b,c)

range(0, 3)
0 1 2


In [21]:
# 2.3 별표(*)를 이용한 언패킹

first, *middle, last = [1, 2, 3, 4, 5]
print(first)    # 출력: 1
print(middle)   # 출력: [2, 3, 4]
print(last)     # 출력: 5


1
[2, 3, 4]
5


# 3. 리스트

In [23]:
# 리스트에는 여러 자료형을 넣어도 됨

z = [1, 'apple', 2.5, ['a', 'b'], (1, 2)]
print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])


1
apple
2.5
['a', 'b']
(1, 2)


In [24]:
# 3.2 리스트 값 수정

a = [1, 2, 3, 4, 5]
a[0] = 10000 # 재할당
print(a)

[10000, 2, 3, 4, 5]


In [25]:
# 3. 리스트안에 리스트

b = [[10,20,30],[1,2,3]]
print(b[1][2])

3


In [28]:
print(b)
print(b[1])
print(b[0][0])

[[10, 20, 30], [1, 2, 3]]
[1, 2, 3]
10


In [29]:
# 리스트의 덧셈

a = [1, 2, 3, 4, 5]
b = [6, 7, 8]

print(a + b) # 출력: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [33]:

l = [1, 2, 3]
print(type(l))
print(l)
print(l * 3)
print(l + l)

<class 'list'>
[1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [34]:
import numpy as np

l = [1, 2, 3]
l = np.array(l)
print(type(l))
print(l)
print(l * 3)
print(l + l)
# 너무 당연하게 요소를 붙이는 것이다라고 생각하지 않으셨으면 좋겠습니다.

<class 'numpy.ndarray'>
[1 2 3]
[3 6 9]
[2 4 6]


In [35]:
# 슬라이싱 실습

l = [1, 2, 3, 4, 5]
print(l[:])     # 출력: [1, 2, 3, 4, 5]
print(l[::-1])  # 출력: [5, 4, 3, 2, 1]
print(l[::2])   # 출력: [1, 3, 5]
print(l[0:4][::-1]) # 출력: [4, 3, 2, 1]

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
[1, 3, 5]
[4, 3, 2, 1]
